[2025-03-08T16:00:25.176+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-08T16:00:25.344+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_fire_incidents_dag.extract_data manual__2025-03-08T15:54:25.170028+00:00 [queued]>
[2025-03-08T16:00:25.354+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_fire_incidents_dag.extract_data manual__2025-03-08T15:54:25.170028+00:00 [queued]>
[2025-03-08T16:00:25.354+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-08T16:00:25.372+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): extract_data> on 2025-03-08 15:54:25.170028+00:00
[2025-03-08T16:00:25.384+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=213) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-08T16:00:25.388+0000] {standard_task_runner.py:72} INFO - Started process 215 to run task
[2025-03-08T16:00:25.388+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_fire_incidents_dag', 'extract_data', 'manual__2025-03-08T15:54:25.170028+00:00', '--job-id', '355', '--raw', '--subdir', 'DAGS_FOLDER/fire_incidents_dag.py', '--cfg-path', '/tmp/tmp7bl4d683']
[2025-03-08T16:00:25.390+0000] {standard_task_runner.py:105} INFO - Job 355: Subtask extract_data
[2025-03-08T16:00:25.453+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_fire_incidents_dag.extract_data manual__2025-03-08T15:54:25.170028+00:00 [running]> on host 6bf41cf28e1a
[2025-03-08T16:00:25.544+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@***.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_fire_incidents_dag' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-08T15:54:25.170028+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-08T15:54:25.170028+00:00'
[2025-03-08T16:00:25.545+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-08T16:00:25.545+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-08T16:00:25.545+0000] {logging_mixin.py:190} INFO - Current task name:extract_data state:running start_date:2025-03-08 16:00:25.345211+00:00
[2025-03-08T16:00:25.546+0000] {logging_mixin.py:190} INFO - Dag name:etl_fire_incidents_dag and current dag run status:running
[2025-03-08T16:00:25.546+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-08T16:00:25.547+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: extract_fire_incidents_data() missing 1 required positional argument: 'parameters'
[2025-03-08T16:00:25.558+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-08T16:00:25.558+0000] {logging_mixin.py:190} INFO - Task start:2025-03-08 16:00:25.345211+00:00 end:2025-03-08 16:00:25.557831+00:00 duration:0.21262
[2025-03-08T16:00:25.559+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): extract_data> dag:<DAG: etl_fire_incidents_dag> dagrun:<DagRun etl_fire_incidents_dag @ 2025-03-08 15:54:25.170028+00:00: manual__2025-03-08T15:54:25.170028+00:00, state:running, queued_at: 2025-03-08 15:54:25.185196+00:00. externally triggered: True>
[2025-03-08T16:00:25.559+0000] {logging_mixin.py:190} INFO - Failure caused by extract_fire_incidents_data() missing 1 required positional argument: 'parameters'
[2025-03-08T16:00:25.559+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_fire_incidents_dag, task_id=extract_data, run_id=manual__2025-03-08T15:54:25.170028+00:00, execution_date=20250308T155425, start_date=20250308T160025, end_date=20250308T160025
[2025-03-08T16:00:25.596+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-08T16:00:25.597+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 355 for task extract_data (extract_fire_incidents_data() missing 1 required positional argument: 'parameters'; 215)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: extract_fire_incidents_data() missing 1 required positional argument: 'parameters'
[2025-03-08T16:00:25.645+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-08T16:00:25.665+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-08T16:00:25.667+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
